### PR TITLE
genus added to all "uroboros" nouns

### PR DESCRIPTION
**Pull request by makrai**
Now formulae are parsed to graphs in which there is an edge from the print name to each clause. We discussed that it may be better to have a clause, practically the fist one, which is a semantic head or genus. Now I modified the definitions of "uroboros" nouns (I mean the ones that are marked with "u" in the 6th field) so that the fist clause is a genus, at leaset when I could do this. Please check the definitions and merge the PR if you like them. (tsv structure is OK, as I checked with the parser.) Now I go on with uroboros words in other parts of speech.

### CODE REVIEW

**Comment by makrai** [comment]
@recski could you please merge this?

**Comment by recski** [comment]
Have you run the tests that I mentioned? (see https://github.com/kornai/pymachine/pull/13)
You need to make sure that you don't break anything (or if you don't care, you can always work in your own fork).

**Comment by makrai** [comment]
This is a separate request concerning only the definitions.

**Comment by recski** [comment]
You should still test it. It takes about 1 minute.

**Comment by makrai** [comment]
I tested it with the definition parser, as I wrote in the first post in this PR. Now I will try to install the whole system.

**Comment by makrai** [comment]
I checked it, and it works
```
(4lang) makrai@nessie:~/repo/4lang$ git pull makrai genus
From github.com:makrai/4lang
 * branch            genus      -> FETCH_HEAD
Auto-merging 4lang
Merge made by the 'recursive' strategy.
 4lang | 308 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------
 1 file changed, 154 insertions(+), 154 deletions(-)
(4lang) makrai@nessie:~/repo/4lang$ python src/fourlang/lexicon.py conf/default.cfg 
2016-10-28 13:51:08,955 : lexicon (29) - INFO - parsing 4lang definitions...
2016-10-28 13:51:08,955 : definition_parser (525) - WARNING - WILL NOW DISCARD ALL BUT THE FIRST DEFINITION OF EACH         HEADWORD!
2016-10-28 13:54:28,095 : lexicon (33) - INFO - parsed 2813 entries, done!
2016-10-28 13:54:28,096 : lexicon (34) - INFO - lowercasing binaries...
2016-10-28 13:54:28,158 : lexicon (40) - INFO - done!
2016-10-28 13:54:28,161 : lexicon (57) - INFO - saving lexicon to /home/makrai/repo/4lang/data/machines/4lang.pickle...
2016-10-28 13:54:28,612 : lexicon (66) - INFO - done!
```

**Pull request merged**
