### PR TITLE
Elim hapax bins

### PR DESCRIPTION
**Pull request by makrai**
especially @recski 
I eliminated some rare binaries. Please check if this seems useful.

### CODE REVIEW

**Comment by recski** [comment]
@makrai Sure it is, thanks.
I only looked at a couple (I don't need to go through all). In case of "brass", why not replace BLOW with blow? It is already defined in 4lang

**Comment by makrai** [comment]
Originally I wanted `brass <-2- blow` that can be expressed only with a capital ("small caps") `BLOW`. I think that we see casing  (in formulas vs in machine print-names (=graph node labels)) differently, so we may discuss it tomorrow or whenever.

**Comment by makrai** [comment]
@recski , what do you think about this request now?
I think that upper-case BLOW don't mean anything too serious, because
* binaries don't have to be primitive, and
* casing is only for the formula (mini)syntax, with no consequence for the graphs

**Comment by makrai** [comment]
I realized that I requested a pull to master, but my branch contains changes from recski_thesis, so I reopen the request there.

**Pull request closed without merging**
