### PR TITLE
disambigauation clean-up

### PR DESCRIPTION
**Pull request by makrai**
clean-up related to disambigauation @recski 
- missing disambigauation inserted
- words for which only one sense has a definition will not be disambiguated and other senses won't redirect
- some comments deleted

### CODE REVIEW

**Comment by makrai** [comment]
In this post, I copy a comment by @DavidNemeskey. My answer follows in a next post.
In many cases, 4lang definitions contain words that appear more than one time as headwords, yet they are not disambiguated with /. See bellow a list of the ones where the word in question has two non-empty definitions (after lowercasing).

[4lang_ambig.txt](https://github.com/DavidNemeskey/Management/files/306274/4lang_ambig.txt)

**Comment by makrai** [comment]
Here I copy a bug report by @DavidNemeskey that he posted in a different repo. My answer follows in a next post.

> In many cases, 4lang definitions contain words that appear more than one time as headwords, yet they are not disambiguated with /. See the error list below (only the ones where the word in question has two non-empty definitions (after lowercasing)).

https://github.com/DavidNemeskey/Management/files/306274/4lang_ambig.txt

**Comment by makrai** [comment]
@recski how do you now handle words that have more definitions in 4lang? If you take the first one, I could rearrange them so that the fist be the intended default.

**Comment by makrai** [comment]
@DavidNemeskey could you please share the updated error list?

**Comment by DavidNemeskey** [comment]
@makrai It's the last one in the Management issue.

**Comment by DavidNemeskey** [comment]
@makrai We merged the PL / nectar PR's, please fix the conflicts in this branch.

**Comment by makrai** [comment]
I think that this pull request would have been useful (removing disambiguation from concepts that have only one defined sense), but the commits are no longer useful because of the divergence, so I close the PR.

**Pull request closed without merging**
